version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-dev
    ports:
      - "5678:5678"
    environment:
      - N8N_CUSTOM_EXTENSIONS=/data/custom-nodes
      - N8N_LOG_LEVEL=debug
      # 设置时区
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
    volumes:
      # n8n 数据持久化
      - ./n8n-data:/home/node/.n8n
      # 挂载编译后的自定义节点
      - ./dist:/data/custom-nodes
      - ./node_modules/xml-js:/usr/local/lib/node_modules/n8n/node_modules/xml-js
    restart: unless-stopped

